ui/src/pages/service-group/plugin/index.ts
ui/src/pages/service-group/plugin/plugin.tsx
ui/src/pages/service-group/service-group.tsx

EPMDJ-7870: Add SG plugin

---

ui/src/modules/plugins-settings-tab/plugins-settings-tab.tsx
ui/src/pages/agent/agent-page.tsx

Fixed: 
- read notification when open build page
- Add plugin modal not work
- Link to plugin from settings

EPMDJ-7876

---

src/ui/pages/agent/agent-page.tsx
src/ui/pages/dashboard/dashboard.tsx
src/ui/pages/service-group/service-group.tsx

EPMDJ-8188: Fix empty Dashboard page when opening the Notification pane

---

src/ui/pages/dashboard/dashboard.tsx

EPMDJ-8190: Add dashboard stub

---

package-lock.json
src/ui/components/toolbar/toolbar.tsx
src/ui/pages/agent-registration-page/agent-registration-page.tsx
src/ui/pages/agent/agent-page.tsx
src/ui/pages/service-group-registration-page/service-group-registration-page.tsx
src/ui/pages/service-group/service-group.tsx
src/ui/root.component.tsx

EPMDJ-8193: Refactor notification pane modal display logic

---

src/ui/components/plugin-list-entry/plugin-list-entry.tsx
src/ui/modules/install-plugins-step/install-plugins-step.tsx
src/ui/modules/plugins-settings-tab/plugins-settings-tab.tsx
src/ui/pages/dashboard/dashboard.tsx

EPMDJ-8190: Align dashboard stub and add border on plugin setting page

---

src/index.ejs

EPMDJ-8130: Fix the icon not displayed after refresh page

---

src/ui/modules/plugins-settings-tab/add-plugins-modal/selectable-list/selectable-list.tsx
src/ui/pages/settings-page/agent-settings/js-system-settings-form/js-system-settings-form.tsx

EPMDJ-8137: Fix checkbox color and js agent setting layout

---

src/ui/components/wizard/wizard.tsx
src/ui/pages/agent-registration-page/agent-registration-page.tsx
src/ui/root.component.tsx

EPMDJ-8273: Fix wizard reinitialization after submit

---

package-lock.json
package.json
src/ui/pages/dashboard/dashboard.tsx

EPMDJ-8283: Fix dashboard error without plugins installed

---

src/ui/pages/agent/plugin/plugin.tsx

EPMDJ-8284: The "Test2Code" overview page from another agent opens

---

src/ui/components/page-header/page-header.tsx
src/ui/pages/agents-page/agents-page.tsx

EPMDJ-7978: Fix agents page header height

---

src/Drill4J-admin-ui-container.ts
webpack.config.js

EPMDJ-8291: Add version log

---

Dockerfile

Package manager:   apk
Project name:      docker-image|drill4j/admin-ui-root-config
Docker image:      drill4j/admin-ui-root-config:latest
Platform:          linux/amd64
Base image:        nginx:1.17.6-alpine-perl
Tested 40 dependencies for known vulnerabilities, found 28 vulnerabilities.
Base Image                Vulnerabilities  Severity
nginx:1.17.6-alpine-perl  28               17 high, 10 medium, 1 low
Recommendations for base image upgrade:
Minor upgrades
Base Image                Vulnerabilities  Severity
nginx:1.21.1-alpine-perl  0                0 high, 0 medium, 0 low

EPMDJ-8331 found 28 vulnerabilities

---

src/index.ejs
src/ui/pages/agent-registration-page/agent-registration-page.tsx
src/ui/pages/agent-registration-page/java-general-registration-form/java-general-registration-form.tsx
src/ui/pages/agent-registration-page/js-general-registration-form/js-general-registration-form.tsx
src/ui/pages/agents-page/agents-page.tsx

EPMDJ-7410: Add validation to agentId on preregistration page

---

src/ui/components/wizard/wizard.tsx
src/ui/pages/agent-registration-page/agent-registration-page.tsx

EPMDJ-7410: Fix incorrect validation message and not displayed plugins selectable list

---

src/ui/modules/breadcrumbs/breadcrumbs.tsx

EPMDJ-8461: Fix load plugin routes

---

package-lock.json
package.json
src/ui/notification-manager/notification-manager.tsx

EPMDJ-8481: Refactor throttle to reconnecting error message

---

src/ui/hooks/use-plugin-urls.ts

EPMDJ-8469 show user friendly error message after load plugin-urls

---

package-lock.json
package.json
src/index.ejs
src/ui/index.css

EPMDJ-8684: Fix form-groups

---

src/ui/pages/builds/builds.tsx

EPMDJ-9414: Update builds page
